{% set name = "compass" %}
{% set version = "0.1.11" %}
{% set build = 0 %}

{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: {{ build }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  # `PKG_NAME * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_py_h{{ PKG_HASH }}_{{ build }}"

requirements:
  run:
    - python
    - geometric_features 0.1.11
    - mpas_tools 0.0.13
    - jigsaw 0.9.12
    - jigsawpy 0.2.1
    - metis
    - cartopy_offlinedata
    - ffmpeg
    - {{ mpi }}  # [mpi != 'nompi']
    - esmf * {{ mpi_prefix }}_*
    - netcdf4 * nompi_*
    - nco
    - pyremap >=0.0.7,<0.1.0
    - rasterio
    - affine
    - ipython
    - jupyter

test:
  imports:
    - geometric_features
    - mpas_tools
    - jigsawpy
  commands:
    - gpmetis --help
    - ffmpeg -help

about:
  home: https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop/testing_and_setup/compass
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A metapackage for creating test cases in the Model for Prediction Across Scales'
  description: |
    A metapackage of all the tools needed by COMPASS (Configuration Of Model
    for Prediction Across Scales Setups), a framework for setting up and running
    ocean and land-ice test cases in the Model for Prediction Across Scales
    (MPAS) framework.
  doc_url: https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/README_ocean.md
  dev_url: https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop/testing_and_setup/compass

extra:
  recipe-maintainers:
    - xylar
