#!/usr/bin/env python
'''
Interpolate fields from an input file to a pre-existing MPAS-LI grid.

The input file can either be CISM format or MPASLI format.

For CISM input files, three interpolation methods are supported:
* a built-in bilinear interpolation method
* a built-in barycentric interpolation method (nearest neighbor is used for
  extrapolation regions)
* using weights generated by ESMF

For MPAS input files only barycentric interpolation is supported.

The ESMF interpolation method can be used to interpolate from history files
of other E3SM components by using the ESMF weight mapping files used in the
E3SM coupler.  You will likely need to add your own variable mappings in the
dictionary for the 'other' filetype at the end of this script.

Multiple time levels can be interpolated using the --timestart and --timeend
options. Default is to copy the first time level from the source file to the
first time level of the destination file.  If multiple time levels are used,
they are translated directly from the source to the destination.
NOTE: There is no processing of actual time stamps!
NOTE: xtime is NOT copied and must be copied manually, if desired!
'''
from mpas_tools.landice.interpolate import interpolate_to_mpasli_grid


if __name__ == '__main__':
    interpolate_to_mpasli_grid()
