name: Documentation Publishing Workflow

on:
  push:
    branches:
      - master

  release:
    types: [published]

env:
  PYTHON_VERSION: "3.13"

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Conda Environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: mpas_tools_dev
          init-shell: bash
          condarc: |
            channel_priority: strict
            channels:
                - conda-forge
          create-args: >-
            python=${{ env.PYTHON_VERSION }}

      - name: Install mpas_tools
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          conda install -y --file conda_package/dev-spec.txt \
            python=${{ env.PYTHON_VERSION }}
          python -m pip install -vv --no-deps --no-build-isolation -e conda_package

      - name: Build Sphinx Docs
        run: |
          set -e
          cd conda_package/docs
          DOCS_VERSION=${{ github.ref_name }} make versioned-html
      - name: Copy Docs and Commit
        run: |
          set -e
          cd conda_package/docs
          # gh-pages branch must already exist
          git clone https://github.com/MPAS-Dev/MPAS-Tools.git --branch gh-pages --single-branch gh-pages

          # Only replace docs in a directory with the destination branch name with latest changes. Docs for
          # releases should be untouched.
          rm -rf gh-pages/${{ github.ref_name }}

          # don't clobber existing release versions (in case we retroactively fixed them)
          cp -r _build/html/${{ github.ref_name }} gh-pages/

          mkdir -p gh-pages/shared
          cp shared/version-switcher.js gh-pages/shared/version-switcher.js

          # Update the list of versions with all versions in the gh-pages directory.
          python generate_versions_json.py

          # Make sure we're in the gh-pages directory.
          cd gh-pages
          # Create `.nojekyll` (if it doesn't already exist) for proper GH Pages configuration.
          touch .nojekyll
          # Add `index.html` to point to the `master` branch automatically.
          printf '<meta http-equiv="refresh" content="0; url=./master/index.html" />' > index.html
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # The second command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: conda_package/docs/gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

